### ISSUE TITLE
Как исправить ошибки блога?

### ISSUE THREAD

**Issue by vladimi1r** [den1n/nova-blog#1]
подскажите пожалуйста, что нужно сделать чтоб сгенерировать стили frontend страницы? когда обращаюсь по пути domain.ru/blog стили не отображаются, заранее спасибо

**Comment by vladimi1r** [comment]
стили нашел в vendor\den1n\nova-blog\resources\sass\frontend.scss 
переменные $font-size-lg $font-size-sm;  имеют неизвестную величину

в инструкции написано 

Add noba-blog components provided by the package to file resources\js\app.js before Vue initialization.

require('./vendor/nova-blog');
Add noba-blog styles provided by the package to file resources\sass\app.scss.

@import './vendor/nova-blog';

не могу понять, что они импортируют? так как путь не полный

очень хочу оживить Ваш блог, подскажите пожалуйста где взять рабочую версию?

**Comment by den1n** [comment]
Для начала нужно опубликовать ресурсы пакета командой:

`php artisan vendor:publish --provider="Den1n\NovaBlog\ServiceProvider"`

Эта команда, помимо прочего, опубликует ресурсы для фронтенда в корень вашего проекта:

- resources/js/vendor/nova-blog
- resources/sass/vendor/nova-blog

После, добавьте в ваши app.js и app.scss указанные импорты, которые импортируют опубликованные ранее ресурсы.

> переменные $font-size-lg $font-size-sm; имеют неизвестную величину

Это стандартные переменные Bootstrap, когда вы добавите импорт

`@import './vendor/nova-blog';`

в ваш app.scss, эти переменные подхватятся из app.scss.
